// api/classify.js
// Vercel serverless function. Receives a raw support-ticket text and returns
// a structured triage result (priority, category, sentiment, suggested reply)
// generated by Claude — the same logic pattern as the n8n IT Support Ticket
// Triage System project, rebuilt here as a live, hosted, single-endpoint tool.
//
// Deploy notes (see README.md for the full walkthrough):
//   1. Set an environment variable ANTHROPIC_API_KEY in your Vercel project
//      settings (Project → Settings → Environment Variables). Never commit
//      the key itself to source control.
//   2. This function only ever runs server-side — the key is never sent to
//      the browser.

export default async function handler(req, res) {
  if (req.method !== "POST") {
    res.status(405).json({ error: "Use POST." });
    return;
  }

  const { ticket } = req.body || {};

  if (!ticket || typeof ticket !== "string" || ticket.trim().length < 5) {
    res.status(400).json({ error: "Paste a ticket with at least a few words of detail." });
    return;
  }

  if (ticket.length > 4000) {
    res.status(400).json({ error: "That's a lot of ticket — trim it to under 4000 characters." });
    return;
  }

  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    res.status(500).json({ error: "Server is missing ANTHROPIC_API_KEY. See README.md." });
    return;
  }

  const systemPrompt = `You are the triage engine behind an internal IT support desk.
Given one raw support ticket (email or chat message from an employee), you produce a
structured triage decision. You never invent facts not implied by the ticket text.

Respond with ONLY a JSON object, no markdown fences, no commentary, in exactly this shape:
{
  "priority": "Low" | "Medium" | "High" | "Critical",
  "category": string,          // short category label, e.g. "Password Reset", "Network Access", "Hardware Failure"
  "sentiment": "Neutral" | "Frustrated" | "Urgent/Escalated" | "Appreciative",
  "confidence": number,        // 0-100, your confidence in this classification
  "reasoning": string,         // ONE sentence explaining the priority call
  "suggested_reply": string    // a short, professional draft reply (2-4 sentences) a support agent could send as-is or lightly edit
}`;

  try {
    const upstream = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-api-key": apiKey,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: "claude-sonnet-4-5",
        max_tokens: 1024,
        system: systemPrompt,
        messages: [{ role: "user", content: ticket.trim() }],
      }),
    });

    if (!upstream.ok) {
      const detail = await upstream.text();
      res.status(502).json({ error: "Claude API request failed.", detail: detail.slice(0, 300) });
      return;
    }

    const data = await upstream.json();
    const raw = data?.content?.[0]?.text ?? "";

    // Claude is asked to return raw JSON, but sometimes wraps it in a
    // ```json ... ``` fence or adds a stray sentence around it. Strip fences
    // and pull out the first {...} block before parsing, instead of failing
    // on the very first JSON.parse attempt.
    function extractJson(text) {
      let t = text.trim();
      const fenced = t.match(/```(?:json)?\s*([\s\S]*?)```/i);
      if (fenced) t = fenced[1].trim();
      const start = t.indexOf("{");
      const end = t.lastIndexOf("}");
      if (start !== -1 && end !== -1 && end > start) {
        t = t.slice(start, end + 1);
      }
      return t;
    }

    let parsed;
    try {
      parsed = JSON.parse(raw);
    } catch {
      try {
        parsed = JSON.parse(extractJson(raw));
      } catch {
        res.status(502).json({
          error:
            data?.stop_reason === "max_tokens"
              ? "Claude's response got cut off before it finished. Try a shorter ticket, or try again."
              : "Could not parse Claude's response as JSON.",
          raw: raw.slice(0, 500),
        });
        return;
      }
    }

    res.status(200).json(parsed);
  } catch (err) {
    res.status(500).json({ error: "Unexpected server error.", detail: String(err) });
  }
}
