// api/classify.js
// Vercel serverless function. Receives a raw support-ticket text and returns
// a structured triage result (priority, category, sentiment, suggested reply)
// generated by Claude — the same logic pattern as the n8n IT Support Ticket
// Triage System project, rebuilt here as a live, hosted, single-endpoint tool.
//
// This endpoint is retrieval-augmented. The flow is:
//
//   1. RETRIEVE — BM25-rank the knowledge base against the ticket text and take
//      the top matches. Most articles are never sent to the model.
//   2. AUGMENT  — inject only those articles into the prompt, tagged by ID.
//   3. GENERATE — Claude drafts a reply grounded in the retrieved steps, and
//      reports which article IDs it actually used.
//
// When retrieval returns nothing, the model is told so explicitly and instructed
// to acknowledge and route rather than invent remediation steps. That is the
// point of grounding: an ungrounded answer should be visibly ungrounded, not a
// confident guess.
//
// Deploy notes (see README.md for the full walkthrough):
//   1. Set an environment variable ANTHROPIC_API_KEY in your Vercel project
//      settings (Project → Settings → Environment Variables). Never commit the
//      key itself to source control.
//   2. This function only ever runs server-side — the key is never sent to
//      the browser.

import { retrieve, buildContext } from "../lib/knowledge-base.js";

/**
 * Fallback used only when no ANTHROPIC_API_KEY is configured, so the interface
 * stays explorable without credentials.
 *
 * Note what is and isn't simulated: retrieval is genuine — BM25 runs locally and
 * needs no API — so the scores and cited articles below are real output. Only the
 * classification and the written reply are canned, and the UI says so.
 */
function demoResponse(ticket, retrieved) {
  const text = ticket.toLowerCase();
  const urgent = /(urgent|asap|immediately|critical|down|outage|cannot work|blocked|all (customers|users)|board call)/.test(text);
  const calm = /(no rush|not urgent|when you get a chance|whenever|no hurry)/.test(text);
  const grateful = /(thank|thanks|appreciate|great job)/.test(text);

  const top = retrieved[0];
  const priority = urgent ? "Critical" : calm ? "Low" : top ? "Medium" : "Low";

  const reply = top
    ? `Thanks for flagging this — I've logged it as ${priority.toLowerCase()} priority and it's with the right team now. ` +
      `Based on our knowledge base (${top.id}: ${top.title}), the first steps we'll work through are covered in our standard runbook. ` +
      `I'll follow up as soon as there's an update.`
    : `Thanks for getting in touch. This one doesn't match anything in our IT knowledge base, so I'm routing it to the right team rather than guessing at a fix. Someone will come back to you shortly.`;

  return {
    demo_mode: true,
    priority,
    category: top ? top.category : "General Enquiry",
    sentiment: grateful ? "Appreciative" : urgent ? "Urgent/Escalated" : "Neutral",
    confidence: top ? Math.min(95, Math.round(60 + top.score * 2)) : 40,
    reasoning: top
      ? `Matched knowledge base article ${top.id} with a BM25 score of ${top.score}; priority inferred from the language used in the ticket.`
      : "No knowledge base article scored above the relevance threshold, so no remediation steps were supplied.",
    sources_used: top ? [top.id] : [],
    suggested_reply: reply,
    retrieval: {
      grounded: retrieved.length > 0,
      retrieved: retrieved.map((r, i) => ({
        id: r.id,
        title: r.title,
        category: r.category,
        score: r.score,
        cited: i === 0,
      })),
    },
  };
}

export default async function handler(req, res) {
  if (req.method !== "POST") {
    res.status(405).json({ error: "Use POST." });
    return;
  }

  const { ticket } = req.body || {};

  if (!ticket || typeof ticket !== "string" || ticket.trim().length < 5) {
    res.status(400).json({ error: "Paste a ticket with at least a few words of detail." });
    return;
  }

  if (ticket.length > 4000) {
    res.status(400).json({ error: "That's a lot of ticket — trim it to under 4000 characters." });
    return;
  }

  const apiKey = process.env.ANTHROPIC_API_KEY;

  // --- 1. RETRIEVE -----------------------------------------------------------
  const retrieved = retrieve(ticket.trim(), { topK: 2 });
  const context = buildContext(retrieved);

  // With no key configured, still answer — retrieval runs locally and needs no
  // API at all, so the retrieval trace shown here is the real thing. Only the
  // written reply is stubbed, and the UI labels it as such.
  if (!apiKey) {
    res.status(200).json(demoResponse(ticket.trim(), retrieved));
    return;
  }

  // --- 2. AUGMENT ------------------------------------------------------------
  const groundingBlock = context
    ? `You have been given the following knowledge base articles, retrieved as the closest
matches to this ticket. Base any remediation steps ONLY on these articles. Do not add steps
from your own general knowledge — if the retrieved articles do not cover the issue, say so.

${context}`
    : `No knowledge base article matched this ticket. Do NOT invent remediation steps.
Acknowledge the issue, tell the user it is being routed to the right team, and leave the
technical detail out. Return an empty "sources_used" array.`;

  const systemPrompt = `You are the triage engine behind an internal IT support desk.
Given one raw support ticket (email or chat message from an employee), you produce a
structured triage decision. You never invent facts not implied by the ticket text.

${groundingBlock}

Respond with ONLY a JSON object, no markdown fences, no commentary, in exactly this shape:
{
  "priority": "Low" | "Medium" | "High" | "Critical",
  "category": string,          // short category label, e.g. "Password Reset", "Network Access", "Hardware Failure"
  "sentiment": "Neutral" | "Frustrated" | "Urgent/Escalated" | "Appreciative",
  "confidence": number,        // 0-100, your confidence in this classification
  "reasoning": string,         // ONE sentence explaining the priority call
  "sources_used": string[],    // the KB article IDs you actually used, e.g. ["KB-01"]. Empty if none applied.
  "suggested_reply": string    // a short, professional draft reply (2-4 sentences) a support agent could send as-is or lightly edit
}`;

  try {
    // --- 3. GENERATE ---------------------------------------------------------
    const upstream = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-api-key": apiKey,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: "claude-sonnet-4-5",
        max_tokens: 1024,
        system: systemPrompt,
        messages: [{ role: "user", content: ticket.trim() }],
      }),
    });

    if (!upstream.ok) {
      const detail = await upstream.text();
      res.status(502).json({ error: "Claude API request failed.", detail: detail.slice(0, 300) });
      return;
    }

    const data = await upstream.json();
    const raw = data?.content?.[0]?.text ?? "";

    // Claude is asked to return raw JSON, but sometimes wraps it in a
    // ```json ... ``` fence or adds a stray sentence around it. Strip fences
    // and pull out the first {...} block before parsing, instead of failing
    // on the very first JSON.parse attempt.
    function extractJson(text) {
      let t = text.trim();
      const fenced = t.match(/```(?:json)?\s*([\s\S]*?)```/i);
      if (fenced) t = fenced[1].trim();
      const start = t.indexOf("{");
      const end = t.lastIndexOf("}");
      if (start !== -1 && end !== -1 && end > start) {
        t = t.slice(start, end + 1);
      }
      return t;
    }

    let parsed;
    try {
      parsed = JSON.parse(raw);
    } catch {
      try {
        parsed = JSON.parse(extractJson(raw));
      } catch {
        res.status(502).json({
          error:
            data?.stop_reason === "max_tokens"
              ? "Claude's response got cut off before it finished. Try a shorter ticket, or try again."
              : "Could not parse Claude's response as JSON.",
          raw: raw.slice(0, 500),
        });
        return;
      }
    }

    // The model reports which articles it used, but it can only legitimately use
    // what retrieval handed it. Intersect the two so a claimed citation to an
    // article that was never retrieved cannot reach the response.
    const retrievedIds = new Set(retrieved.map((r) => r.id));
    const claimed = Array.isArray(parsed.sources_used) ? parsed.sources_used : [];
    const verifiedIds = claimed.filter((id) => retrievedIds.has(id));

    res.status(200).json({
      ...parsed,
      sources_used: verifiedIds,
      // Full retrieval trace, so the UI can show what was considered and not just
      // what was cited — the evidence trail behind the answer.
      retrieval: {
        grounded: verifiedIds.length > 0,
        retrieved: retrieved.map((r) => ({
          id: r.id,
          title: r.title,
          category: r.category,
          score: r.score,
          cited: verifiedIds.includes(r.id),
        })),
      },
    });
  } catch (err) {
    res.status(500).json({ error: "Unexpected server error.", detail: String(err) });
  }
}
